/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.games.rps.controller;

import com.games.rps.dto.JwtTokenDTO;
import com.games.rps.dto.LoginUserDTO;
import io.swagger.annotations.*;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@RequestMapping(value = "/api")
@Api(value = "authenticate", description = "the authenticate API")
    public interface AuthenticateApi {
    @ApiOperation(value = "Registers User by ID", nickname = "authenticate", notes = "", response = JwtTokenDTO.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = JwtTokenDTO.class),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/authenticate",
        method = RequestMethod.POST)
    JwtTokenDTO authenticate(@ApiParam(value = "The user to create."  )  @Valid @RequestBody LoginUserDTO loginUser);

}
