/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.games.rps.controller;

import com.games.rps.dto.OnePlayResultDTO;
import com.games.rps.dto.PlayItemDTO;
import com.games.rps.dto.RpcStatDTO;
import com.games.rps.dto.StartResultDTO;
import io.swagger.annotations.*;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@RequestMapping(value = "/api")
@Api(value = "me", description = "the me API")
    public interface MeApi {
    @ApiOperation(value = "Starts rocket-paper-scissors game session", nickname = "playRpc", notes = "", response = OnePlayResultDTO.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = OnePlayResultDTO.class),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/me/playrpc",
        method = RequestMethod.POST)
    OnePlayResultDTO playRpc(@ApiParam(value = "The one from Rocket, Paper or Scissors."  )  @Valid @RequestBody PlayItemDTO item);

    @ApiOperation(value = "Starts rocket-paper-scissors game session", nickname = "startRpc", notes = "", response = StartResultDTO.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StartResultDTO.class),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/me/startrpc",
        method = RequestMethod.POST)
    StartResultDTO startRpc();

    @ApiOperation(value = "Stops rocket-paper-scissors game session", nickname = "stopRpc", notes = "", response = RpcStatDTO.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RpcStatDTO.class),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/me/stoprpc",
        method = RequestMethod.POST)
    RpcStatDTO stopRpc();

}
