/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.games.rps.controller;

import com.games.rps.dto.UserDTO;
import io.swagger.annotations.*;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@RequestMapping(value = "/api")
@Api(value = "user", description = "the user API")
    public interface UserApi {
    @ApiOperation(value = "Retrieves User by ID", nickname = "getUserById", notes = "", response = UserDTO.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UserDTO.class),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/user/{id}",
        method = RequestMethod.GET)
    UserDTO getUserById(@ApiParam(value = "retrieves user by user id",required=true) @PathVariable("id") Integer id);

}
