swagger: '3.0'
info:
  description: "Codegen for demo service"
  version: "0.0.1"
  title: "Demo Service Specification"
  contact:
    email: "antonie.zafirov@47northlabs.com"
tags:
  - name: "user"
    description: "User tag for demo purposes"
#servers:
#  - url: http://localhost:8000/api
#    description: "local host"
host: localhost:8000
basePath: /api
schemes:
  - https
  - http
paths:
  /user/{id}:
    get:
      tags:
        - "user"
      summary: "Retrieves User by ID"
      operationId: "getUserById"
      parameters:
        - name: "id"
          in: "path"
          description: "retrieves user by user id"
          required: true
          type: "integer"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            $ref: "#/definitions/User"
        404:
          description: NOT FOUND
  /authenticate:
    post:
      tags:
        - "user"
      summary: "Registers User by ID"
      operationId: "authenticate"
      contentType: "application/json"
      parameters:
        - in: body
          name: loginUser
          description: The user to create.
          type: object
          schema:
            $ref: "#/definitions/LoginUser"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            $ref: "#/definitions/JwtToken"
        404:
          description: NOT FOUND
definitions:
  User:
    type: "object"
    required:
      - "id"
      - "firstName"
      - "lastName"
      - "dateOfBirth"
      - "gender"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
        example: "John"
      lastName:
        type: "string"
        example: "Smith"
      dateOfBirth:
        type: "string"
        example: "1992-10-05"
      gender:
        type: "string"
        enum:
          - "MALE"
          - "FEMALE"
          - "UNKNOWN"
  LoginUser:
    type: "object"
    required:
      - "username"
      - "password"
    properties:
      username:
        type: string
      password:
        type: string
  JwtToken:
    type: "object"
    properties:
      token:
        type: string




