swagger: '3.0'
info:
  description: "Rocket Paper Scissors game backend"
  version: "0.0.1"
  title: "Rocket Paper Scissors game backend"
tags:
  - name: "user"
    description: "User tag for demo purposes"
basePath: /api
schemes:
  - https
  - http
paths:
  /me/startrpc:
    post:
      tags:
        - "user"
      summary: "Starts rocket-paper-scissors game session"
      operationId: "startRpc"
      responses:
        200:
          description: OK
          type: object
          schema:
            $ref: "#/definitions/StartResult"
        404:
          description: NOT FOUND
  /me/playrpc:
    post:
      tags:
        - "user"
      summary: "Starts rocket-paper-scissors game session"
      operationId: "playRpc"
      parameters:
        - in: body
          name: item
          description: The one from Rocket, Paper or Scissors.
          type: object
          schema:
            $ref: "#/definitions/PlayItem"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            $ref: "#/definitions/OnePlayResult"
        404:
          description: NOT FOUND
  /me/stoprpc:
    post:
      tags:
        - "user"
      summary: "Stops rocket-paper-scissors game session"
      operationId: "stopRpc"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            $ref: "#/definitions/RpcStat"
        404:
          description: NOT FOUND
  /authenticate:
    post:
      tags:
        - "user"
      summary: "Registers User by given username and password"
      operationId: "authenticate"
      contentType: "application/json"
      parameters:
        - in: body
          name: loginUser
          description: The user to create.
          type: object
          schema:
            $ref: "#/definitions/LoginUser"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            $ref: "#/definitions/JwtToken"
        404:
          description: NOT FOUND
definitions:
  LoginUser:
    type: "object"
    required:
      - "username"
      - "password"
    properties:
      username:
        type: string
      password:
        type: string
  JwtToken:
    type: "object"
    properties:
      token:
        type: string
  RpcStat:
    type: "object"
    properties:
      totalGames:
        type: integer
      totalWins:
        type: integer
      totalLost:
        type: integer
      totalDraws:
        type: integer
      lastSessionGames:
        type: integer
      lastSessionWins:
        type: integer
      lastSessionLost:
        type: integer
      lastSessionDraws:
        type: integer
  OnePlayResult:
    type: "object"
    properties:
      myItem:
        type: object
        $ref: "#/definitions/PlayItem"
      computerItem:
        type: object
        $ref: "#/definitions/PlayItem"
      result:
        type: string
        enum:
          - I_WON
          - COMPUTER_WON
          - DRAW
  PlayItem:
    type: object
    properties:
      item:
        type: string
        enum:
          - ROCKET
          - PAPER
          - SCISSORS
  StartResult:
    type: object
    properties:
      item:
        type: string
        enum:
          - STARTED
          - NOT_STARTED




